In [8]:
import numpy as np
import pandas as pd

df = pd.read_csv(
    'AAPL.csv',
    index_col = False,
    parse_dates = ['Date']
)
df

,Date,Open,High,Low,Close,Adj Close,Volume
0,2015-12-31,107.010002,107.029999,104.820000,105.260002,98.657883,40912300
1,2016-01-04,102.610001,105.370003,102.000000,105.349998,98.742249,67649400
2,2016-01-05,105.750000,105.849998,102.410004,102.709999,96.267815,55791000
3,2016-01-06,100.559998,102.370003,99.870003,100.699997,94.383888,68457400
4,2016-01-07,98.680000,100.129997,96.430000,96.449997,90.400467,81094400
5,2016-01-08,98.550003,99.110001,96.760002,96.959999,90.878479,70798000
6,2016-01-11,98.970001,99.059998,97.339996,98.529999,92.350006,49739400
7,2016-01-12,100.550003,100.690002,98.839996,99.959999,93.690300,49154200
8,2016-01-13,100.320000,101.190002,97.300003,97.389999,91.281494,62439600
9,2016-01-14,97.959999,100.480003,95.739998,99.519997,93.277916,63170100
10,2016-01-15,96.199997,97.709999,95.360001,97.129997,91.037811,79833900
11,2016-01-19,98.410004,98.650002,95.500000,96.660004,90.597290,53087700
12,2016-01-20,95.099998,98.190002,93.419998,96.790001,90.719131,72334400
13,2016-01-21,97.059998,97.879997,94.940002,96.300003,90.259872,52161500
14,2016-01-22,98.629997,101.459999,98.370003,101.419998,95.058739,65800500
15,2016-01-25,101.519997,101.529999,99.209999,99.440002,93.202934,51794500
16,2016-01-26,99.930000,100.879997,98.070000,99.989998,93.718437,75077000
17,2016-01-27,96.040001,96.629997,93.339996,93.419998,87.560509,133369700
18,2016-01-28,93.790001,94.519997,92.389999,94.089996,88.188484,55678800
19,2016-01-29,94.790001,97.339996,94.349998,97.339996,91.234650,64416500
20,2016-02-01,96.470001,96.709999,95.400002,96.430000,90.381721,40943500
21,2016-02-02,95.419998,96.040001,94.279999,94.480003,88.554024,37357200
22,2016-02-03,95.000000,96.839996,94.080002,96.349998,90.306725,45964300
23,2016-02-04,95.860001,97.330002,95.190002,96.599998,91.032356,46471700
24,2016-02-05,96.519997,96.919998,93.690002,94.019997,88.601059,46418100
25,2016-02-08,93.129997,95.699997,93.040001,95.010002,89.533989,54021400
26,2016-02-09,94.290001,95.940002,93.930000,94.989998,89.515144,44331200
27,2016-02-10,95.919998,96.349998,94.099998,94.269997,88.836655,42343600
28,2016-02-11,93.790001,94.720001,92.589996,93.699997,88.299492,50074700
29,2016-02-12,94.190002,94.500000,93.010002,93.989998,88.572784,40351400
...,...,...,...,...,...,...,...
871,2019-06-19,199.679993,199.880005,197.309998,197.869995,197.121048,21124200
872,2019-06-20,200.369995,200.610001,198.029999,199.460007,198.705032,21514000
873,2019-06-21,198.800003,200.850006,198.149994,198.779999,198.027603,47800600
874,2019-06-24,198.539993,200.160004,198.169998,198.580002,197.828369,18220400
875,2019-06-25,198.429993,199.259995,195.289993,195.570007,194.829758,21070300
876,2019-06-26,197.770004,200.990005,197.350006,199.800003,199.043747,26067500
877,2019-06-27,200.289993,201.570007,199.570007,199.740005,198.983978,20899700
878,2019-06-28,198.679993,199.500000,197.050003,197.919998,197.170853,31110600
879,2019-07-01,203.169998,204.490005,200.649994,201.550003,200.787125,27316700
880,2019-07-02,201.410004,203.130005,201.360001,202.729996,201.962646,16935200
881,2019-07-03,203.279999,204.440002,202.690002,204.410004,203.636292,11362000
882,2019-07-05,203.350006,205.080002,202.899994,204.229996,203.456970,17265500
883,2019-07-08,200.809998,201.399994,198.410004,200.020004,199.262909,25338600
884,2019-07-09,199.199997,201.509995,198.809998,201.240005,200.478302,20578000
885,2019-07-10,201.850006,203.729996,201.559998,203.229996,202.460754,17897100
886,2019-07-11,203.309998,204.389999,201.710007,201.750000,200.986359,20191800
887,2019-07-12,202.449997,204.000000,202.199997,203.300003,202.530502,17595200
888,2019-07-15,204.089996,205.869995,204.000000,205.210007,204.433273,16947400
889,2019-07-16,204.589996,206.110001,203.500000,204.500000,203.725952,16866800
890,2019-07-17,204.050003,205.089996,203.270004,203.350006,202.580307,14107500
891,2019-07-18,204.000000,205.880005,203.699997,205.660004,204.881561,18582200
892,2019-07-19,205.789993,206.500000,202.360001,202.589996,201.823181,20929300
893,2019-07-22,203.649994,207.229996,203.610001,207.220001,206.435654,22277900
894,2019-07-23,208.460007,208.910004,207.289993,208.839996,208.049515,18355200
895,2019-07-24,207.669998,209.149994,207.169998,208.669998,207.880173,14991600
896,2019-07-25,208.889999,209.240005,206.729996,207.020004,206.236420,13909600
897,2019-07-26,207.479996,209.729996,207.139999,207.740005,206.953690,17618900
898,2019-07-29,208.460007,210.639999,208.440002,209.679993,208.886337,21673400
899,2019-07-30,208.759995,210.160004,207.309998,208.779999,207.989746,33935700
900,2019-07-31,216.419998,221.369995,211.300003,213.039993,212.233627,69281400

In [2]:
df.columns = ['Est','Tes']
df

NameError: name 'df' is not defined

In [4]:
df['selisih']= df.apply(lambda baris : baris['Est'] - baris['Close'], axis =1)
df

NameError: name 'df' is not defined

,Date,Open,High,Low,Close,Adj Close,Volume,selisih
0,2015-12-31,107.010002,107.029999,104.820000,105.260002,98.657883,40912300,1.750000
1,2016-01-04,102.610001,105.370003,102.000000,105.349998,98.742249,67649400,-2.739997
2,2016-01-05,105.750000,105.849998,102.410004,102.709999,96.267815,55791000,3.040001
3,2016-01-06,100.559998,102.370003,99.870003,100.699997,94.383888,68457400,-0.139999
4,2016-01-07,98.680000,100.129997,96.430000,96.449997,90.400467,81094400,2.230003
5,2016-01-08,98.550003,99.110001,96.760002,96.959999,90.878479,70798000,1.590004
6,2016-01-11,98.970001,99.059998,97.339996,98.529999,92.350006,49739400,0.440002
7,2016-01-12,100.550003,100.690002,98.839996,99.959999,93.690300,49154200,0.590004
8,2016-01-13,100.320000,101.190002,97.300003,97.389999,91.281494,62439600,2.930001
9,2016-01-14,97.959999,100.480003,95.739998,99.519997,93.277916,63170100,-1.559998
10,2016-01-15,96.199997,97.709999,95.360001,97.129997,91.037811,79833900,-0.930000
11,2016-01-19,98.410004,98.650002,95.500000,96.660004,90.597290,53087700,1.750000
12,2016-01-20,95.099998,98.190002,93.419998,96.790001,90.719131,72334400,-1.690003
13,2016-01-21,97.059998,97.879997,94.940002,96.300003,90.259872,52161500,0.759995
14,2016-01-22,98.629997,101.459999,98.370003,101.419998,95.058739,65800500,-2.790001
15,2016-01-25,101.519997,101.529999,99.209999,99.440002,93.202934,51794500,2.079995
16,2016-01-26,99.930000,100.879997,98.070000,99.989998,93.718437,75077000,-0.059998
17,2016-01-27,96.040001,96.629997,93.339996,93.419998,87.560509,133369700,2.620003
18,2016-01-28,93.790001,94.519997,92.389999,94.089996,88.188484,55678800,-0.299995
19,2016-01-29,94.790001,97.339996,94.349998,97.339996,91.234650,64416500,-2.549995
20,2016-02-01,96.470001,96.709999,95.400002,96.430000,90.381721,40943500,0.040001
21,2016-02-02,95.419998,96.040001,94.279999,94.480003,88.554024,37357200,0.939995
22,2016-02-03,95.000000,96.839996,94.080002,96.349998,90.306725,45964300,-1.349998
23,2016-02-04,95.860001,97.330002,95.190002,96.599998,91.032356,46471700,-0.739997
24,2016-02-05,96.519997,96.919998,93.690002,94.019997,88.601059,46418100,2.500000
25,2016-02-08,93.129997,95.699997,93.040001,95.010002,89.533989,54021400,-1.880005
26,2016-02-09,94.290001,95.940002,93.930000,94.989998,89.515144,44331200,-0.699997
27,2016-02-10,95.919998,96.349998,94.099998,94.269997,88.836655,42343600,1.650001
28,2016-02-11,93.790001,94.720001,92.589996,93.699997,88.299492,50074700,0.090004
29,2016-02-12,94.190002,94.500000,93.010002,93.989998,88.572784,40351400,0.200004
...,...,...,...,...,...,...,...,...
871,2019-06-19,199.679993,199.880005,197.309998,197.869995,197.121048,21124200,1.809998
872,2019-06-20,200.369995,200.610001,198.029999,199.460007,198.705032,21514000,0.909988
873,2019-06-21,198.800003,200.850006,198.149994,198.779999,198.027603,47800600,0.020004
874,2019-06-24,198.539993,200.160004,198.169998,198.580002,197.828369,18220400,-0.040009
875,2019-06-25,198.429993,199.259995,195.289993,195.570007,194.829758,21070300,2.859986
876,2019-06-26,197.770004,200.990005,197.350006,199.800003,199.043747,26067500,-2.029999
877,2019-06-27,200.289993,201.570007,199.570007,199.740005,198.983978,20899700,0.549988
878,2019-06-28,198.679993,199.500000,197.050003,197.919998,197.170853,31110600,0.759995
879,2019-07-01,203.169998,204.490005,200.649994,201.550003,200.787125,27316700,1.619995
880,2019-07-02,201.410004,203.130005,201.360001,202.729996,201.962646,16935200,-1.319992
881,2019-07-03,203.279999,204.440002,202.690002,204.410004,203.636292,11362000,-1.130005
882,2019-07-05,203.350006,205.080002,202.899994,204.229996,203.456970,17265500,-0.879990
883,2019-07-08,200.809998,201.399994,198.410004,200.020004,199.262909,25338600,0.789994
884,2019-07-09,199.199997,201.509995,198.809998,201.240005,200.478302,20578000,-2.040008
885,2019-07-10,201.850006,203.729996,201.559998,203.229996,202.460754,17897100,-1.379990
886,2019-07-11,203.309998,204.389999,201.710007,201.750000,200.986359,20191800,1.559998
887,2019-07-12,202.449997,204.000000,202.199997,203.300003,202.530502,17595200,-0.850006
888,2019-07-15,204.089996,205.869995,204.000000,205.210007,204.433273,16947400,-1.120011
889,2019-07-16,204.589996,206.110001,203.500000,204.500000,203.725952,16866800,0.089996
890,2019-07-17,204.050003,205.089996,203.270004,203.350006,202.580307,14107500,0.699997
891,2019-07-18,204.000000,205.880005,203.699997,205.660004,204.881561,18582200,-1.660004
892,2019-07-19,205.789993,206.500000,202.360001,202.589996,201.823181,20929300,3.199997
893,2019-07-22,203.649994,207.229996,203.610001,207.220001,206.435654,22277900,-3.570007
894,2019-07-23,208.460007,208.910004,207.289993,208.839996,208.049515,18355200,-0.379989
895,2019-07-24,207.669998,209.149994,207.169998,208.669998,207.880173,14991600,-1.000000
896,2019-07-25,208.889999,209.240005,206.729996,207.020004,206.236420,13909600,1.869995
897,2019-07-26,207.479996,209.729996,207.139999,207.740005,206.953690,17618900,-0.260009
898,2019-07-29,208.460007,210.639999,208.440002,209.679993,208.886337,21673400,-1.219986
899,2019-07-30,208.759995,210.160004,207.309998,208.779999,207.989746,33935700,-0.020004
900,2019-07-31,216.419998,221.369995,211.300003,213.039993,212.233627,69281400,3.380005