In [1]:
import numpy as np
import pandas as pd

df = pd.read_csv(
    'data-histori-saham.csv',
    index_col=False,
    parse_dates=['Tanggal'])
df.set_index('Tanggal', inplace=True)
df = df.sort_index()
df

            Kode  Open  Close  Change(Rp)  Change(%)     Volume
Tanggal
2016-01-04  TLKM  3105   3140          35       1.13   53937600
2016-01-05  TLKM  3140   3195          55       1.75  111298000
2016-01-06  TLKM  3195   3250          55       1.72  126669200
2016-01-07  TLKM  3250   3210         -40      -1.23  106056300
2016-01-08  TLKM  3210   3145         -65      -2.02  121217800
...          ...   ...    ...         ...        ...        ...
2019-07-28  TLKM  4160   4160         -50      -1.20   70952400
2019-07-29  TLKM  4150   4200          40       1.00   44515800
2019-07-30  TLKM  4270   4270          70       1.70   88417200
2019-07-31  TLKM  4240   4300          30       0.70  172610000
2019-08-01  TLKM  4300   4280         -20      -0.50   27204600

[859 rows x 6 columns]

In [2]:
df['2016-01':'2017-01']

            Kode  Open  Close  Change(Rp)  Change(%)     Volume
Tanggal
2016-01-04  TLKM  3105   3140          35       1.13   53937600
2016-01-05  TLKM  3140   3195          55       1.75  111298000
2016-01-06  TLKM  3195   3250          55       1.72  126669200
2016-01-07  TLKM  3250   3210         -40      -1.23  106056300
2016-01-08  TLKM  3210   3145         -65      -2.02  121217800
...          ...   ...    ...         ...        ...        ...
2017-01-24  TLKM  3840   3910          70       1.82  113430200
2017-01-25  TLKM  3910   3900         -10      -0.26   47799100
2017-01-26  TLKM  3900   3940          40       1.03   60944600
2017-01-27  TLKM  3940   3890         -50      -1.27   47240400
2017-01-30  TLKM  3890   3860         -30      -0.77   30060700

[264 rows x 6 columns]

In [4]:
df = df.loc['2017-10-02']['Close']
df

4680